# Netlify Build Settings
[build]
  command = "npm run build"      # The command to build your React site
  publish = "dist"               # The folder that contains the built site (Vite's default)
  functions = "netlify/functions" # The folder where our serverless functions live

# Environment Variables
[build.environment]
  VITE_N8N_WELCOME_WEBHOOK_URL = "https://rafaello.app.n8n.cloud/webhook/decision"
  N8N_FILTER_WEBHOOK_URL = "https://rafaello.app.n8n.cloud/webhook/filter"
  N8N_DECISION_WEBHOOK_URL = "https://rafaello.app.n8n.cloud/webhook/brain"

# Redirects and Rewrites
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

  [functions]
  external_node_modules = ["stripe"]