# Netlify Build Settings
[build]
  command = "npm run build"      # The command to build your React site
  publish = "dist"               # The folder that contains the built site (Vite's default)
  functions = "netlify/functions" # The folder where our serverless functions live

# Redirects and Rewrites
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200