[build]
  functions = "netlify/functions"
  publish = "build"
  command = "npm run build"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[functions."stripe-webhook"]
  node_bundler = "esbuild"
  external_node_modules = ["stripe", "@netlify/functions"]

[functions."send-welcome-email"]
  node_bundler = "esbuild"
  external_node_modules = ["resend", "node-fetch"]

[functions."handle-verification"]
  node_bundler = "esbuild"
  external_node_modules = ["resend", "@supabase/supabase-js"]

  [[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
  force  = true
